### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by eaedk** [DelphinKdl/-Data-analysis-project-Data-Driven-Insights-for-Indian-Startup-Growth#1]
Feedback to share with your team:

1. Structure your repository with folders
2. Improve your Readme to make it appealing, add images, screenshots, sections like contacts/contributors, article or dashboard link, etc.
3. Describe a bit more the project in the readme.

**Comment by DelphinKdl** [comment]
all the mentioned issues was reviewed and fixed
